/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2014-04-09 07:57:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.org.debux.webmotion.pollmotion;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <title>PollMotion</title>\n");
      out.write("\n");
      out.write("        <!-- Le styles -->\n");
      out.write("        <link href=\"http://twitter.github.com/bootstrap/assets/css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            body {\n");
      out.write("                padding-top: 20px;\n");
      out.write("                padding-bottom: 40px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            /* Custom container */\n");
      out.write("            .container-narrow {\n");
      out.write("                margin: 0 auto;\n");
      out.write("                max-width: 700px;\n");
      out.write("            }\n");
      out.write("            .container-narrow > hr {\n");
      out.write("                margin: 30px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            /* Main marketing message and sign up button */\n");
      out.write("            .jumbotron {\n");
      out.write("                margin: 60px 0;\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("            .jumbotron h1 {\n");
      out.write("                font-size: 72px;\n");
      out.write("                line-height: 1;\n");
      out.write("            }\n");
      out.write("            .jumbotron .btn {\n");
      out.write("                font-size: 21px;\n");
      out.write("                padding: 14px 24px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            /* Supporting marketing content */\n");
      out.write("            .marketing {\n");
      out.write("                margin: 60px 0;\n");
      out.write("            }\n");
      out.write("            .marketing p + h4 {\n");
      out.write("                margin-top: 28px;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <link href=\"http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\n");
      out.write("        <!--[if lt IE 9]>\n");
      out.write("          <script src=\"http://twitter.github.com/bootstrap/assets/js/html5shiv.js\"></script>\n");
      out.write("        <![endif]-->\n");
      out.write("\n");
      out.write("        <!-- Fav and touch icons -->\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png\">\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png\">\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png\">\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" href=\"http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png\">\n");
      out.write("        <link rel=\"shortcut icon\" href=\"http://twitter.github.com/bootstrap/assets/ico/favicon.png\">\n");
      out.write("        \n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/jquery.js\"></script>\n");
      out.write("        <sitemesh:write property='head'/>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <div class=\"container-narrow\">\n");
      out.write("            \n");
      out.write("            <div class=\"masthead\">\n");
      out.write("                <ul class=\"nav nav-pills pull-right\">\n");
      out.write("                    <li class=\"active\"><a href=\"./index\">Home</a></li>\n");
      out.write("                    <li><a href=\"#\">About</a></li>\n");
      out.write("                    <li><a href=\"#\">Contact</a></li>\n");
      out.write("                </ul>\n");
      out.write("                <h3 class=\"muted\">PollMotion</h3>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <sitemesh:write property='body'/>\n");
      out.write("                \n");
      out.write("            <hr>\n");
      out.write("\n");
      out.write("            <div class=\"footer\">\n");
      out.write("                <p>&copy; WebMotion 2013</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Placed at the end of the document so the pages load faster -->\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-transition.js\"></script>\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-alert.js\"></script>\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-modal.js\"></script>\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js\"></script>\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-scrollspy.js\"></script>\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-tab.js\"></script>\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-tooltip.js\"></script>\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-popover.js\"></script>\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-button.js\"></script>\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-collapse.js\"></script>\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-carousel.js\"></script>\n");
      out.write("        <script src=\"http://twitter.github.com/bootstrap/assets/js/bootstrap-typeahead.js\"></script>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
